name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .
      - name: Analyze project source
        run: flutter analyze --fatal-infos

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flutter-version: ['stable', 'beta']
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.flutter-version }}
          channel: ${{ matrix.flutter-version }}
      - name: Install dependencies
        run: flutter pub get
      - name: Run tests
        run: flutter test
      
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: Install lcov
        run: sudo apt-get install lcov
      - name: Run tests with coverage
        run: flutter test --coverage
      - name: Generate coverage report
        run: genhtml coverage/lcov.info -o coverage/html
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: coverage/lcov.info
          fail_ci_if_error: false
          
  pana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: Install pana
        run: dart pub global activate pana
      - name: Run pana
        run: dart pub global run pana --no-warning --source path .

  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: Build Android example
        run: |
          cd example
          flutter build apk --debug

  build-ios:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: Build iOS example
        run: |
          cd example
          flutter build ios --debug --no-codesign

  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: Build Web example
        run: |
          cd example
          flutter build web
